# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ijExVAJQrhN8LCRfLquD0yD6XDshMNb
"""

# # Customer Churn Prediction using a Neural Network

# In this notebook I am trying to predict whether a telecom customer will churn
# based on their plan, usage and behavior. I'll go step by step — first
# understanding the data, then preparing it, building a simple feed-forward
# network and finally trying a few different settings to see what works best.

# basic libs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# sklearn stuff for preprocessing + metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (confusion_matrix, classification_report,
                             roc_auc_score, ConfusionMatrixDisplay)

# tensorflow / keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

import warnings
warnings.filterwarnings("ignore")

# fix seeds so results don't change every run
np.random.seed(42)
tf.random.set_seed(42)

# folder to save outputs
os.makedirs("results", exist_ok=True)

sns.set_style("whitegrid")
print("TF version:", tf.__version__)

# ## Task 1 — Dataset Understanding

# analysing the data-how many rows, what kind
# of columns, any missing values, and how the churn class is distributed.

df = pd.read_csv("/customer_churn_nn.csv")

print("Rows, Columns:", df.shape)
df.head()

# quick check on dtypes
df.info()

# missing values?
print("Missing values per column:")
print(df.isnull().sum())

# basic stats
df.describe()

# categorical columns - just to see what categories exist
cat_cols = ['region', 'plan_type', 'contract_type', 'payment_method']
for c in cat_cols:
    print(f"\n{c}:")
    print(df[c].value_counts())

print("Churn counts:")
print(df['churn'].value_counts())
print(f"\nChurn rate: {df['churn'].mean()*100:.2f} %")

fig, ax = plt.subplots(1, 2, figsize=(11, 4))

df['churn'].value_counts().plot(
    kind='bar', ax=ax[0], color=['#4C72B0', '#DD8452'])
ax[0].set_title("Churn Count")
ax[0].set_xticklabels(['Retained (0)', 'Churned (1)'], rotation=0)

df['churn'].value_counts(normalize=True).plot(
    kind='pie', autopct='%1.1f%%', ax=ax[1],
    colors=['#4C72B0', '#DD8452'],
    labels=['Retained', 'Churned'])
ax[1].set_ylabel("")
ax[1].set_title("Churn Share")

plt.tight_layout()
plt.savefig("results/target_distribution.png", dpi=120, bbox_inches='tight')
plt.show()

# #What I noticed:**

# - 2000 rows, 17 columns. Looks small but workable.
# - No missing values (lucky for us).
# - `customer_id` is just an ID, not useful for prediction.
# - Four categorical columns and the rest numeric.
# - The target is **very imbalanced** — only a small percentage of customers
#   actually churn. So plain accuracy won't be very meaningful here; I'll also
#   look at ROC-AUC and recall on the churn class.

#Task 2 — Data Preprocessing

# Steps:
# 1. Drop `customer_id` (it's only an identifier)
# 2. One-hot encode categorical columns
# 3. Train/Test split with stratify so churn ratio is preserved
# 4. Scale numeric values with StandardScaler
# 5. Compute class weights to deal with imbalance

data = df.drop(columns=['customer_id'])

X = data.drop(columns=['churn'])
y = data['churn']

# one-hot encode categoricals
X = pd.get_dummies(X, columns=cat_cols, drop_first=True)

# IMPORTANT: pd.get_dummies sometimes gives bool dtype in newer pandas,
# tensorflow doesn't like that, so convert to float
X = X.astype(float)

print("Feature matrix shape:", X.shape)
X.head()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print("Train:", X_train_sc.shape, "  Test:", X_test_sc.shape)
print("Train churn rate:", round(y_train.mean()*100, 2), "%")
print("Test  churn rate:", round(y_test.mean()*100, 2), "%")

# class weights -- since churn class is rare
weights = compute_class_weight(class_weight='balanced',
                               classes=np.array([0, 1]),
                               y=y_train)
class_weights = {0: weights[0], 1: weights[1]}
print("Class weights ->", class_weights)

# ## Task 3 — Building the Neural Network

# I'll build a simple feed-forward network:
# - input layer takes all features
# - 2 hidden layers with ReLU
# - output layer with sigmoid (binary classification)
# - loss = binary cross-entropy, optimizer = Adam

# Wrapping it in a function so I can reuse it for the experiments later.

def build_model(input_dim, hidden_layers=(32, 16),
                activation='relu', learning_rate=0.001):
    model = Sequential()
    model.add(Dense(hidden_layers[0], activation=activation,
                    input_dim=input_dim))
    for units in hidden_layers[1:]:
        model.add(Dense(units, activation=activation))
    model.add(Dense(1, activation='sigmoid'))   # output

    model.compile(optimizer=Adam(learning_rate=learning_rate),
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

input_dim = X_train_sc.shape[1]
model = build_model(input_dim)
model.summary()

# ## Task 4 — Train & Evaluate

# I'll use EarlyStopping so the model stops once val_loss isn't improving.
# Also passing class_weight to handle imbalance.

es = EarlyStopping(monitor='val_loss', patience=10,
                   restore_best_weights=True)

history = model.fit(X_train_sc, y_train,
                    validation_split=0.2,
                    epochs=80,
                    batch_size=32,
                    class_weight=class_weights,
                    callbacks=[es],
                    verbose=1)

train_loss, train_acc = model.evaluate(X_train_sc, y_train, verbose=0)
test_loss,  test_acc  = model.evaluate(X_test_sc,  y_test,  verbose=0)

print(f"Train -> loss: {train_loss:.4f} | acc: {train_acc:.4f}")
print(f"Test  -> loss: {test_loss:.4f} | acc: {test_acc:.4f}")

# predictions
y_prob = model.predict(X_test_sc).flatten()
y_pred = (y_prob >= 0.5).astype(int)

print(f"\nROC-AUC: {roc_auc_score(y_test, y_prob):.4f}")
print("\nClassification report:")
print(classification_report(y_test, y_pred,
                            target_names=['Retained', 'Churned']))

fig, ax = plt.subplots(1, 2, figsize=(13, 4))

ax[0].plot(history.history['loss'], label='train')
ax[0].plot(history.history['val_loss'], label='val')
ax[0].set_title("Loss")
ax[0].set_xlabel("epoch")
ax[0].legend()

ax[1].plot(history.history['accuracy'], label='train')
ax[1].plot(history.history['val_accuracy'], label='val')
ax[1].set_title("Accuracy")
ax[1].set_xlabel("epoch")
ax[1].legend()

plt.tight_layout()
plt.savefig("results/evaluation_outputs.png", dpi=120, bbox_inches='tight')
plt.show()

cm = confusion_matrix(y_test, y_pred)

fig, ax = plt.subplots(figsize=(5, 4))
ConfusionMatrixDisplay(cm,
    display_labels=['Retained', 'Churned']).plot(cmap='Blues', ax=ax)
plt.title("Confusion Matrix")
plt.savefig("results/confusion_matrix.png", dpi=120, bbox_inches='tight')
plt.show()

##What this tells me:**
##- The overall accuracy looks high but that's mostly because most customers don't churn. So I should look more at recall for the churn class.
##- The AUC score is a better indicator of how well the model separates the two classes.
##- Loss curves drop smoothly which means training was stable.

## Task 5 — Hyperparameter Experiments

##Trying 5 different settings — changing depth, learning rate, activation,and batch size to see how each affects results.

experiments = [
    {'name': 'Exp1_Baseline',       'hidden': (32, 16),      'lr': 0.001, 'bs': 32,  'epochs': 50, 'act': 'relu'},
    {'name': 'Exp2_DeeperNet',      'hidden': (64, 32, 16),  'lr': 0.001, 'bs': 32,  'epochs': 50, 'act': 'relu'},
    {'name': 'Exp3_HighLR',         'hidden': (32, 16),      'lr': 0.01,  'bs': 32,  'epochs': 50, 'act': 'relu'},
    {'name': 'Exp4_TanhActivation', 'hidden': (32, 16),      'lr': 0.001, 'bs': 32,  'epochs': 50, 'act': 'tanh'},
    {'name': 'Exp5_LargeBatch',     'hidden': (32, 16),      'lr': 0.001, 'bs': 128, 'epochs': 50, 'act': 'relu'},
]

results = []

for e in experiments:
    print(f"Running {e['name']} ...")
    # reset seed each time so it's fair
    tf.random.set_seed(42)
    np.random.seed(42)

    m = build_model(input_dim,
                    hidden_layers=e['hidden'],
                    activation=e['act'],
                    learning_rate=e['lr'])

    m.fit(X_train_sc, y_train,
          validation_split=0.2,
          epochs=e['epochs'],
          batch_size=e['bs'],
          class_weight=class_weights,
          verbose=0)

    tr_acc = m.evaluate(X_train_sc, y_train, verbose=0)[1]
    te_acc = m.evaluate(X_test_sc,  y_test,  verbose=0)[1]
    auc = roc_auc_score(y_test, m.predict(X_test_sc, verbose=0).flatten())

    results.append({
        'Experiment'   : e['name'],
        'Hidden Layers': str(e['hidden']),
        'Activation'   : e['act'],
        'Learning Rate': e['lr'],
        'Batch Size'   : e['bs'],
        'Epochs'       : e['epochs'],
        'Train Acc'    : round(tr_acc, 4),
        'Test Acc'     : round(te_acc, 4),
        'Test AUC'     : round(auc, 4),
    })

comp_df = pd.DataFrame(results)
comp_df.to_csv("results/model_comparison_table.csv", index=False)
comp_df

fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(comp_df))

ax.bar(x - 0.2, comp_df['Train Acc'], 0.4, label='Train', color='#4C72B0')
ax.bar(x + 0.2, comp_df['Test Acc'],  0.4, label='Test',  color='#DD8452')

ax.set_xticks(x)
ax.set_xticklabels(comp_df['Experiment'], rotation=20, ha='right')
ax.set_ylabel("Accuracy")
ax.set_title("Train vs Test Accuracy across experiments")
ax.legend()

plt.tight_layout()
plt.savefig("results/model_comparison_chart.png", dpi=120, bbox_inches='tight')
plt.show()

# ## Task 6 — Reflection

# **1. Role of weights and biases**

# The weights basically decide how much each feature matters when moving from
# one layer to the next. Biases let the neuron shift its output up or down
# even when the input is 0 — so the model has more flexibility. During
# backpropagation these are the things that actually get updated to reduce
# the loss.

# **2. Why we need an activation function**

# If we don't put any activation function, then no matter how many layers we
# stack, the whole network just becomes a fancy linear regression. ReLU /
# sigmoid / tanh add non-linearity which is what lets the network learn
# complex patterns like the kind of customer who is likely to churn.

# **3. Learning rate effects**

# - Too high (like my Exp3 with lr=0.01): the loss kept jumping around and
#   the model never really settled. AUC came out lower.
# - Too low: training would be slow and might stop before learning enough.
# - 0.001 with Adam felt like a sweet spot for this dataset.

# **4. Overfitting or underfitting?**

# In my baseline (Exp1) the train and test accuracy were close, so it
# generalized okay. The deeper network in Exp2 had higher train accuracy but
# test didn't improve much — slight overfitting. Exp3 with high LR was just
# unstable. Overall the baseline gave the best balance.

# Since the data is imbalanced, I trusted the AUC score and the recall for
# the churn class more than plain accuracy.

from google.colab import drive
drive.mount('/content/drive')